name: Build and Release ADR Tool RPM

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

        # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"

        # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
#           ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

        # Install RPM build dependencies
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm golang

        # Run Go tests
      - name: Run Go tests
        run: |
          go test ./...

      # Get version dynamically from Git tag
      - name: Determine Version
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

        # Build ADR tool with version information
      - name: Build ADR tool
        run: |
          go build -ldflags "-X main.version=${VERSION}"  -o adr ./

        # Create tarball dynamically with version
      - name: Create tarball
        run: |
          tar -czf adr-tool-${VERSION}.tar.gz adr 