name: Build & Release with Makefile

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [binary_linux_amd64, binary_linux_arm64, binary_darwin_amd64, binary_darwin_arm64, binary_windows_amd64, binary_windows_arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Install dependencies
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"

      # Install make and other dependencies
      - name: Install make and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make rpm golang ruby ruby-dev

      # Cache Go modules and APT dependencies (optional)
      - name: Cache Go modules and APT dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            /tmp/apt-cache
          key: ${{ runner.os }}-go-apt-${{ hashFiles('**/go.sum', '**/apt-get.lock') }}
          restore-keys: |
            ${{ runner.os }}-go-apt-

      # Run Makefile commands
      - name: Run Makefile Build
        run: |
          go list -m all
          make build

      - name: Run Makefile Tests
        run: make test
      
      # Goes parallel for each target from the matrix (see above)
      - name: Build and package for ${{ matrix.target }}
        run: make ${{ matrix.target }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: adr-*.*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Multi-platform release
          files: |
            dist/**/*
